workflows:
  ios-simulator-build:
    name: Build Solitaire iOS App for Simulator
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "Solitaire.xcodeproj"
        XCODE_SCHEME: "Solitaire"
    scripts:
      - name: Build for iOS Simulator
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -sdk iphonesimulator \
                     -configuration Debug | xcpretty
