workflows:
  ios-build:
    name: Build Solitaire iOS App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "Solitaire.xcodeproj"  # Your project file
        XCODE_SCHEME: "Solitaire"            # App's scheme name
    scripts:
      - name: Install CocoaPods dependencies (if any)
        script: |
          gem install cocoapods --user-install || echo "CocoaPods not required"
      - name: Build the app
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGN_STYLE=Manual | xcpretty
    artifacts:
      - build/Release-iphoneos/*.ipa
